### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by francopestilli**
hi @skoudoro @guaje @soichih

This is the way I suggest we edit the ReadMe for the DIPY Apps.

Apps should provide information about App goals and operations, the contributors, the scientific papers and the funding. The code used can be referenced at the end of each readme file.

Note that I am suggesting using this as a DIPY App Template. The Template is based on the brainlife.io template: https://github.com/brainlife/app-template-python

Please let e us know!

### CODE REVIEW

**Comment by skoudoro** [comment]
Looks reasonable. We will update them.

**Comment by francopestilli** [comment]
@guaje @skoudoro i just talked to @guaje briefly, it looks like it might be helpful to discuss this. We would like to clarify what the App does on brainlife.io and not remind users to read the documentation about code.

**Comment by skoudoro** [comment]
ok @francopestilli, just let me know when you are available.

**Comment by francopestilli** [comment]
now? @skoudoro https://meet.jit.si/brainlifeanddipynow?

**Pull request merged**
